overrides:
  '@octokit/request-error@>=6.0.0 <6.1.7': '>=6.1.7'
  '@octokit/endpoint@>=10.0.0 <10.1.3': '>=10.1.3'
  esbuild@<=0.24.2: '>=0.25.0'
  vitest@>=2.0.0 <2.1.9: '>=2.1.9'
  '@octokit/request@>=9.0.0-beta.1 <9.2.1': '>=9.2.1'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
