overrides:
  '@eslint/plugin-kit@<0.3.3': '>=0.3.3'
  '@octokit/endpoint@>=10.0.0 <10.1.3': '>=10.1.3'
  '@octokit/plugin-paginate-rest@>=9.3.0-beta.1 <11.4.1': '>=11.4.1'
  '@octokit/request-error@>=6.0.0 <6.1.7': '>=6.1.7'
  '@octokit/request@>=9.0.0-beta.1 <9.2.1': '>=9.2.1'
  brace-expansion: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  vitest@>=2.0.0 <2.1.9: '>=2.1.9'
