name: Validate pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - name: Run linter
        run: pnpm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-pnpm
      - name: Run tests
        run: pnpm run test